# Generated by Django 4.2.6 on 2023-10-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='views',
        ),
        migrations.AddField(
            model_name='vieweduser',
            name='discuss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.discuss'),
        ),
    ]
