# Generated by Django 4.2.6 on 2023-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_discuss_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
