# Generated by Django 4.2.6 on 2023-10-18 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_discuss_views_vieweduser_discuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='views',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ViewedUser',
        ),
    ]
