# Generated by Django 4.2.6 on 2023-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_discuss_views_delete_vieweduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
