# Generated by Django 4.2.6 on 2023-11-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
