# Generated by Django 4.2.6 on 2023-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_discuss_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_body',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
