# Generated by Django 4.2.6 on 2023-11-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_answer_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='watchedTags',
            field=models.ManyToManyField(null=True, related_name='watchedTag', to='base.tag'),
        ),
    ]
