# Generated by Django 4.2.6 on 2023-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tag_tag_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
