# Generated by Django 4.2.6 on 2023-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_tag_tag_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
