# Generated by Django 4.2.6 on 2023-12-05 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_discuss_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='views',
            field=models.ManyToManyField(related_name='viewed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='watchedTags',
            field=models.ManyToManyField(related_name='watchedTag', to='base.tag'),
        ),
    ]
