# Generated by Django 4.2.6 on 2023-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_discuss_is_watching_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='is_watching_or_not',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
